Enhancement/donetodomodel jb
AllisterF1/m46-wk10-group1-backend pull request #16
Opened 2023-05-03 20:11 UTC by joeburnsJB

model for doneTodos

2023-05-03 20:23 UTC, ApacheTech requested changes
Requires a change of name for a field within the model.

2023-05-03 20:23 UTC, ApacheTech commented on src/doneTodos/model.js
> +    completedTasks: {
The design specs say that this field should be called "todo", rather than "completedTasks" (addDoneTodo.txt).

2023-05-03 20:43 UTC, joeburnsJB commented on src/doneTodos/model.js
> +    completedTasks: {
I missed that! Thanks for pointing it out! Just changed it now

2023-05-04 08:01 UTC, ApacheTech reviewed
Should be good now.

2023-05-04 08:01 UTC, ApacheTech approved these changes
Should be good now.

2023-05-04 08:33 UTC, merged